version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile # Asegúrate de que el Dockerfile esté en la carpeta client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
