name: Frontend_Deploy

on:
  push:
    branches:
      - "prod:front" 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

     
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .                          
          file: ./server/Dockerfile           
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/assetly-landing_page-frontend:latest 
            ${{ secrets.DOCKERHUB_USERNAME }}/assetly-landing_page-frontend:${{ github.sha }}
